# Generated by Django 3.2 on 2021-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('HP', 'Haryana'), ('MI', 'Sikkim'), ('GJ', 'Gujarat'), ('MZ', 'Mizoram'), ('KL', 'Kerala'), ('AR', 'Arunachal Pradesh'), ('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('WB', 'West Bengal'), ('PB', 'Punjab'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('ML', 'Meghalaya'), ('TR', 'Tripura'), ('JH', 'Jharkhand'), ('RJ', 'Rajasthan'), ('TS', 'Telegana'), ('CG', 'Chhattisgarh'), ('MP', 'Madhya Pradesh'), ('GA', 'Goa'), ('AS', 'Assam'), ('TN', 'Tamil Nadu'), ('BR', 'Bihar')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Bikes', 'Bikes'), ('Electronics', 'Electronics')], max_length=100),
        ),
    ]
