# Generated by Django 3.2 on 2021-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210518_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('UK', 'Uttarakhand'), ('MI', 'Sikkim'), ('CG', 'Chhattisgarh'), ('MH', 'Maharashtra'), ('AP', 'Andhra Pradesh'), ('GA', 'Goa'), ('WB', 'West Bengal'), ('UP', 'Uttar Pradesh'), ('KA', 'Karnataka'), ('OD', 'Odisha'), ('ML', 'Meghalaya'), ('AR', 'Arunachal Pradesh'), ('TN', 'Tamil Nadu'), ('JH', 'Jharkhand'), ('MN', 'Manipur'), ('GJ', 'Gujarat'), ('AS', 'Assam'), ('KL', 'Kerala'), ('TR', 'Tripura'), ('NL', 'Nagaland'), ('RJ', 'Rajasthan'), ('TS', 'Telegana'), ('HP', 'Haryana'), ('MP', 'Madhya Pradesh'), ('MZ', 'Mizoram'), ('BR', 'Bihar'), ('PB', 'Punjab')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Property', 'Property'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Books&Sports', 'Books&Sports'), ('Jobs', 'Jobs'), ('Cars', 'Cars')], max_length=100),
        ),
    ]
