# Generated by Django 3.2 on 2021-05-19 09:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210518_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('AS', 'Assam'), ('MH', 'Maharashtra'), ('CG', 'Chhattisgarh'), ('BR', 'Bihar'), ('GJ', 'Gujarat'), ('ML', 'Meghalaya'), ('AP', 'Andhra Pradesh'), ('TN', 'Tamil Nadu'), ('WB', 'West Bengal'), ('KA', 'Karnataka'), ('TR', 'Tripura'), ('GA', 'Goa'), ('HP', 'Haryana'), ('PB', 'Punjab'), ('KL', 'Kerala'), ('AR', 'Arunachal Pradesh'), ('UK', 'Uttarakhand'), ('JH', 'Jharkhand'), ('MN', 'Manipur'), ('MP', 'Madhya Pradesh'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('UP', 'Uttar Pradesh'), ('MZ', 'Mizoram'), ('TS', 'Telegana'), ('NL', 'Nagaland'), ('MI', 'Sikkim')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اكسترا سوبر لوكس', 'اكسترا سوبر لوكس'), ('سوبر لوكس', 'سوبر لوكس'), ('لوكس', 'لوكس'), ('نصف تشطيب', 'نصف تشطيب'), ('بدون تشطيب', 'بدون تشطيب'), ('تحت الانشاء', 'تحت الانشاء'), ('تم التسليم', 'تم التسليم'), ('حديقة', 'حديقة'), ('بنتهاوس', 'بنتهاوس'), ('شارع رئيسي', 'شارع رئيسي'), ('بنتهاوس', 'بنتهاوس'), ('شارع فرعي', 'شارع فرعي'), ('البحر النيل', 'البحر النيل'), ('ناصية', 'ناصية'), ('ناصية', 'ناصية')], max_length=142),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Cars', 'Cars'), ('Property', 'Property'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs')], max_length=100),
        ),
    ]
