# Generated by Django 3.2 on 2021-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210519_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('GJ', 'الحي الثالث'), ('CG', 'الحي الاول'), ('AS', 'المتميز'), ('HP', 'الحي الرابع'), ('BR', 'الحصري'), ('JH', 'الحي الحادي عشر'), ('KA', 'الحي اثني عشر'), ('GA', 'الحي التاني'), ('AP', '6 اكتوبر'), ('AR', 'الشيخ زايد')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Books&Sports', 'الاسماعيلية'), ('Jobs', 'راس سدر'), ('Cars', 'الجيزة'), ('Property', 'اسكندرية'), ('Electronics', 'القاهرة الكبري'), ('Mobiles', 'الغردقة'), ('Bikes', 'الفيوم'), ('Fashion', 'العين السخنة'), ('Furniture', 'الساحل الشمالي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_link',
            field=models.URLField(blank=True, max_length=280, null=True),
        ),
    ]
