# Generated by Django 3.2 on 2021-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210519_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longtitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('GA', 'الحي التاني'), ('AP', '6 اكتوبر'), ('KA', 'الحي اثني عشر'), ('AR', 'الشيخ زايد'), ('CG', 'الحي الاول'), ('AS', 'المتميز'), ('BR', 'الحصري'), ('GJ', 'الحي الثالث'), ('HP', 'الحي الرابع'), ('JH', 'الحي الحادي عشر')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Bikes', 'الفيوم'), ('Fashion', 'العين السخنة'), ('Mobiles', 'الغردقة'), ('Electronics', 'القاهرة الكبري'), ('Jobs', 'راس سدر'), ('Furniture', 'الساحل الشمالي'), ('Cars', 'الجيزة'), ('Property', 'اسكندرية'), ('Books&Sports', 'الاسماعيلية')], max_length=100),
        ),
    ]
