# Generated by Django 3.2 on 2021-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210519_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('HP', 'الحي الرابع'), ('KA', 'الحي اثني عشر'), ('AR', 'الشيخ زايد'), ('GJ', 'الحي الثالث'), ('AP', '6 اكتوبر'), ('GA', 'الحي التاني'), ('AS', 'المتميز'), ('JH', 'الحي الحادي عشر'), ('BR', 'الحصري'), ('CG', 'الحي الاول')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Electronics', 'القاهرة الكبري'), ('Property', 'اسكندرية'), ('Mobiles', 'الغردقة'), ('Books&Sports', 'الاسماعيلية'), ('Bikes', 'الفيوم'), ('Furniture', 'الساحل الشمالي'), ('Cars', 'الجيزة'), ('Fashion', 'العين السخنة'), ('Jobs', 'راس سدر')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
