# Generated by Django 3.2 on 2021-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210519_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('المتميز', 'المتميز'), ('الحي الاول', 'الحي الاول'), ('الحي الرابع', 'الحي الرابع'), ('مدينة نصر', 'مدينة نصر'), ('الشيخ زايد', 'الشيخ زايد'), ('الحي الحادي عشر', 'الحي الحادي عشر'), ('الحي الثالث', 'الحي الثالث'), ('الحي اثني عشر', 'الحي اثني عشر'), ('الحي التاني', 'الحي التاني'), ('اكتوبر 6', '6 اكتوبر'), ('الحصري', 'الحصري')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('الجيزة', 'الجيزة'), ('القاهرة الكبري', 'القاهرة الكبري'), ('راس سدر', 'راس سدر'), ('الغردقة', 'الغردقة'), ('العين السخنة', 'العين السخنة'), ('اسكندرية', 'اسكندرية'), ('الفيوم', 'الفيوم'), ('الساحل الشمالي', 'الساحل الشمالي'), ('الاسماعيلية', 'الاسماعيلية')], max_length=100),
        ),
    ]
