# Generated by Django 3.2 on 2021-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210519_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('المتميز', 'المتميز'), ('الحي الاول', 'الحي الاول'), ('الحي التاني', 'الحي التاني'), ('الشيخ زايد', 'الشيخ زايد'), ('الحصري', 'الحصري'), ('الحي الحادي عشر', 'الحي الحادي عشر'), ('الحي اثني عشر', 'الحي اثني عشر'), ('الحي الثالث', 'الحي الثالث'), ('اكتوبر 6', '6 اكتوبر'), ('مدينة نصر', 'مدينة نصر'), ('الحي الرابع', 'الحي الرابع')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('الغردقة', 'الغردقة'), ('الاسماعيلية', 'الاسماعيلية'), ('اسكندرية', 'اسكندرية'), ('القاهرة الكبري', 'القاهرة الكبري'), ('الساحل الشمالي', 'الساحل الشمالي'), ('العين السخنة', 'العين السخنة'), ('الجيزة', 'الجيزة'), ('راس سدر', 'راس سدر'), ('الفيوم', 'الفيوم')], max_length=100),
        ),
    ]
