# Generated by Django 3.2 on 2021-05-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20210519_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('الحي الرابع', 'الحي الرابع'), ('الحي التاني', 'الحي التاني'), ('مدينة نصر', 'مدينة نصر'), ('الحصري', 'الحصري'), ('الحي الثالث', 'الحي الثالث'), ('الحي اثني عشر', 'الحي اثني عشر'), ('الحي الحادي عشر', 'الحي الحادي عشر'), ('الحي الاول', 'الحي الاول'), ('المتميز', 'المتميز'), ('الشيخ زايد', 'الشيخ زايد'), ('اكتوبر 6', '6 اكتوبر')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('الفيوم', 'الفيوم'), ('الجيزة', 'الجيزة'), ('الساحل الشمالي', 'الساحل الشمالي'), ('راس سدر', 'راس سدر'), ('الغردقة', 'الغردقة'), ('القاهرة الكبري', 'القاهرة الكبري'), ('الاسماعيلية', 'الاسماعيلية'), ('العين السخنة', 'العين السخنة'), ('اسكندرية', 'اسكندرية')], max_length=100),
        ),
    ]
