# Generated by Django 3.2 on 2021-05-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20210519_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('الحي الثالث', 'الحي الثالث'), ('الحي التاني', 'الحي التاني'), ('الحي الرابع', 'الحي الرابع'), ('الحصري', 'الحصري'), ('مدينة نصر', 'مدينة نصر'), ('الحي الاول', 'الحي الاول'), ('الحي اثني عشر', 'الحي اثني عشر'), ('المتميز', 'المتميز'), ('الحي الحادي عشر', 'الحي الحادي عشر'), ('اكتوبر 6', '6 اكتوبر'), ('الشيخ زايد', 'الشيخ زايد')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('الساحل الشمالي', 'الساحل الشمالي'), ('الفيوم', 'الفيوم'), ('الجيزة', 'الجيزة'), ('الاسماعيلية', 'الاسماعيلية'), ('العين السخنة', 'العين السخنة'), ('القاهرة الكبري', 'القاهرة الكبري'), ('الغردقة', 'الغردقة'), ('راس سدر', 'راس سدر'), ('اسكندرية', 'اسكندرية')], max_length=100),
        ),
    ]
